### ISSUE TITLE
HTTP Keep alive with range request followed by non range gives wrong response

### ISSUE THREAD

**Issue by Seethaprasad** [NanoHttpd/nanohttpd#126]
In my scenario, HTTP range request is followed by HTTP GET request. This causes wrong data to be sent to the browser and video streaming fails. I was able to reproduce consistently while streaming video to a mobile browser.

Below code is used for keep alive scenario
while (!finalAccept.isClosed()) 
{
      session.execute();

Session is re-used but not all states are cleanly re-initialized after keep alive scenario.

I modified to create a new HTTPSession session for each request even in keep-alive scenario and it works fine. Let me know if this is fine or need to take a different patch.
while (!finalAccept.isClosed()) 
 {
                                    	HTTPSession session = new HTTPSession(tempFileManager, inputStream, outputStream, finalAccept.getInetAddress());
                                        
                                        session.execute();
                                 
 }
                         
The issue mainly caused by headers, thought haveing a new HTTPSession is cleaner.

**Comment by AnjanishKumar** [comment]
I have also faced the same issue while streaming video. After debugging i found the issue and fixed it. The issue comes because the <code>headers</code> variable in the <code>Session</code> class is not being cleared properly. Adding one else clause will fix this issue.
<code>
 if(null == headers) {
                    headers = new HashMap<String, String>();
  } else{
         headers.clear();
}
</code>

Hope this will help you to fix the problem and the author will add this fix in the nanohttpd core.

**Comment by ritchieGitHub** [comment]
was already included in an other bugfix, please reopen if it does not work as expected
