### ISSUE TITLE
cross-domain with http request

### ISSUE THREAD

**Issue by xiaowuzhang** [NanoHttpd/nanohttpd#129]
can you release an android version whithout the cross domain problem when do a http request.
I dispatch your project and change it for working in android.If you want, i can send the modify version.

**Comment by elonen** [comment]
What exactly is the issue (and the fix)?

**Comment by LukeCarrier** [comment]
The issue is with the implementation of HTTP access control (or CORS; cross
origin resource sharing) in clients.

To allow browsers which support CORS to fetch assets which reside on other
domains, the domain hosting the resource must send an appropriate
Access-Control-Allow-Origin header.

I wouldn't consider this to be an issue in NanoHttpd itself -- the
application developer can add the necessary headers into the Response
before sending it.

**Comment by LukeCarrier** [comment]
The issue is with the implementation of HTTP access control (or CORS; cross origin resource sharing) in clients. To allow browsers which support CORS to fetch assets which reside on other
domains, the domain hosting the resource must send an appropriate Access-Control-Allow-Origin header.

I wouldn't consider this to be an issue in NanoHttpd itself, as the application developer can add the necessary headers into the Response before sending it.

**Comment by elonen** [comment]
Thank you for the clarification @LukeCarrier .
Since setting a blanket `Access-Control-Allow-Origin: *` can apparently cause a security risk in certain cases, it's probably better to leave the decision to the user.
For future reference: http://en.wikipedia.org/wiki/Cross-origin_resource_sharing
