### ISSUE TITLE
HTTP Keep-Alive is not working

### ISSUE THREAD

**Issue by andresoviedo** [NanoHttpd/nanohttpd#217]
Is it posible that the HTTP server is reusing the PushBackInputStream to read requests from client, but when it is processed, it does not clear (remove) the data (POST data) not read in the previous request?

I have problems making 2 requests, one after another:
$ curl --data "debug=true" http://localhost:8082/ping 
$ curl http://localhost:8082/servlet1

The first request sends POST data but is not read in the request handler. The POST data is "debug=true"
The second request send a request but the nanohttpd find "debug=truePOST /servlet1), so it crashes.
The exception thrown in "Systax error", line 731:

    this.method = Method.lookup(pre.get("method"));
    if (this.method == null) {
      throw new ResponseException(Response.Status.BAD_REQUEST, "BAD REQUEST: Syntax error.");
    }

**Comment by elonen** [comment]
Sounds plausible. I couldn't reproduce this with SimpleWebServer, though. Guess you have a custom serve() that skips reading the data at the first request (the POST)?

**Comment by elonen** [comment]
Ok, I think I know what's going on. When keep-alive is used, a `serve()` must read the request in its entirety, or otherwise the next request will contain garbage. The default serve does this by calling `parseBody()`, but a custom one might not. I've added function 
`long HTTPSession.getBodySize()` that can be used for easily `this.inputStream.skip()`ing an unused request body. See 0760946.

However, the skipping could (should) actually be done by NanoHTTPD core and not left to user's responsibility. That will require a byte-counting `InputStream` wrapper, so it would probably be wisest to do that simultaneously with fixing issue #211, which requires a custom (chunked) `InputStream` wrapper anyway. OTOH, if someone implements CountingInputStream and the skipping in Core (there's a placeholder TODO in 0760946 for that) before #211, I'd be happy to merge the wrappers later.

**Comment by ritchieGitHub** [comment]
@andresoviedo does the fix work?

**Comment by ritchieGitHub** [comment]
assumed working, if not please reopen

**Comment by andresoviedo** [comment]
Sorry.  I havent tested my system with the latest version.  I keep using my own patch since I discovered it.  However, if I make an update to my application I will use the latest version, so I can evaluate it. 
Thank you very much.
