### ISSUE TITLE
Grab whole URL or URL Fragments from IHTTPSession

### ISSUE THREAD

**Issue by Lokikol** [NanoHttpd/nanohttpd#277]
I start a new Webserver with the serve Method that has an IHTTPSession object.

I use an api, that redirects to this webserver, and generates the following request:

http://mywebserver.com/?state=adsf#otherkey=value

so I want to grab the URL Fragment "otherkey=value" or, the whole url as shown above, so I can use split for # to get the URL Fragment.

How is this possible in NNanoHttpd?

I didn't find any solution.

**Comment by LordFokas** [comment]
You don't use the '#', you use an '&' and then NanoHTTP automatically parses it for you and stores it in a HashMap<String, String>. I think it's called 'parms' or something, it's available on the request object.

**Comment by ritchieGitHub** [comment]
please reopen if there is special need for this feature. (If it is specify the reason why it is needed)

**Comment by BjoernAkAManf** [comment]
Fragment identifier such as #otherkey=value are not send to the server. 
That makes them unprocessable for any webserver.

**Comment by LordFokas** [comment]
That's because those are client-side only. They are processed by the browser AFTER the server's response arrives.

To send data to the server you must either send it in a POST body or use a **query string**, like this
`http://resources.domain.org/images?key1=value1&key2=value2&flag1&key3=value3&flag4` as the request URL.
