### ISSUE TITLE
Intercept file:// scheme requests

### ISSUE THREAD

**Issue by Lingviston** [NanoHttpd/nanohttpd#285]
Sorry if this question is too stupid. I need to intercept file:// scheme requests which are coming from my webview. Is it possible?

Looks like [this](https://github.com/nikkiii/embedhttp) library can do it but it's not under active development.

**Comment by LordFokas** [comment]
It's not.

`file://path/to/file.ext` URLs tell the browser the path refers to a file in the local machine instead of a path in a webserver, and therefore they search the local machine instead of connecting to a server, thus, webservers never receive `file://` "requests". In fact, webservers never receive (at least correctly) anything that isn't based on the HTTP protocol.

NanoHTTPD can handle HTTP, HTTPS, WS and WSS requests (HTTP and WebSockets, either through SSL/TLS or plain text).

**Comment by Lingviston** [comment]
Thanks! Looks like I got a wrong info.
