### ISSUE TITLE
Why pass a empty string to newFixedLengthResponse() when nanohttpd server a default main page file index.htm?

### ISSUE THREAD

**Issue by mycwcgr** [NanoHttpd/nanohttpd#304]
I use nanohttpd as web server in my android. 

There is an index.htm file in my web folder, the nanohttpd will access the default main page file index.htm when I vistit my web server via http://10.7.241.137:8080/.
I found the system launch the code from line 544 to 548, but I'm very suprised that it pass a empty string to newFixedLengthResponse(Response.Status.NOT_MODIFIED, mime, "") and FireFox can display the correct content of index.htm
In my mind, it should pass the file index.htm to newFixedLengthResponse(Response.Status.NOT_MODIFIED, mime, "")! 

 line 544 to 548 

                   // full-file-fetch request
                    // would return entire file
                    // respond with not-modified
                    res = newFixedLengthResponse(Response.Status.NOT_MODIFIED, mime, "");
                    res.addHeader("ETag", etag);

**Comment by LordFokas** [comment]
AFAIK that NOT_MODIFIED means your browser already has the page in cache, in which case it first sends a HEAD request to NanoHTTPD instead of a GET, saying it has a version from a certain date.
NanoHTTPD responds with a NOT_MODIFIED meaning that the file has not been modified since the browser last cached it and therefore the browser doesn't need to request the full file again and can instead use the one it has in cache because it's the same version.
