### ISSUE TITLE
Asynchronous serve

### ISSUE THREAD

**Issue by andredsp** [NanoHttpd/nanohttpd#305]
Is there an easy way to send an async response in the (synchronous) serve() method? I'm not an Android specialist so I may be missing a point here.

**Comment by LordFokas** [comment]
`serve()` isn't synchronous, each socket is being handled by a different thread, where `serve()` is called.

Unless you mean something different, in which case I'll ask you to try to explain yourself better so that we're able to help.

**Comment by andredsp** [comment]
What I meant with `sync()` being synchronous is that I must return a `Response`, but I don't have it right away since I need to call an asynchronous service to get the data.

I need something like `IHTTPSession.send(Response)` which I could call any time I want, even after `serve()` is finished.

Again, I'm an iOS developer so I must be missing something here, because all solutions I found about calling an async method inside a sync one are not straightforward.

**Comment by elonen** [comment]
Since it's in its own thread, you can simply sleep u​ntill you've got the
data to return from serve().

**Comment by andredsp** [comment]
Ok thank you guys.

**Comment by LordFokas** [comment]
Well I guess the "correct" way of doing it is passing the current thread to the async service and then suspend the thread. When the service returns it can cache the response and then interrupt the HTTP thread so that it wakes up.

It's not that it doesn't work, but sleeping is usually only used for timed waiting periods while suspending the thread is more indicated for waiting during undefined periods of time. Just make sure the service invocation is done in a try catch block so that if it fails you don't leave that HTTP thread hanging.

**Comment by iagoFG** [comment]
I think I have the same idea thru my head... why is not Nanohttpd fully async?

Maybe a alternative to the default IAsyncRunner (DefaultAsyncRunner) can be implemented that uses reusable threads instead of threads that are created and destroyed for each request... something like workers.

Also maybe Response.sendBody (and it's call chain) could manage not only one output stream, but a some or maybe all currently opened output streams... at least those which respond to InputStream.available() with greater than 0, or maybe simpler, with greater than bytesToRead... it that way loop does not get locked and can manage lots of output streams at once.

Probably best way is to pass again to IAsyncRunner when output is returned so maybe it's processing can be yield to other thread or something else.
