### ISSUE TITLE
How to use copies of non-threadsafe objects in each thread of the threadpool?

### ISSUE THREAD

**Issue by johann-petrak** [NanoHttpd/nanohttpd#353]
I do not quite understand the way how multithreaded handling of requests work in NanoHTTPD: for example if a thread pool is used, does the serve method which I overwrite run within a thread of that thread pool? How can I then assign some resource to each thread in the thread pool so that I can use that specific resource when handling a request?

The reason why this is necessary is because the resource I want to use during handling of the request (i.e. inside the serve method) is not thread safe. So in order to avoid problems, each concurrent use of that resource needs to use its own copy. So I want to make sure that each thread can have and use its own copy. Since cloning the resource is expensive, I want to use a ThreadPool and assign the copy of the resource to each thread in the ThreadPool when it is created, then use it within serve.

The alternative would be to use my own ThreadPool just for the resource, but if we already have a thread pool for handling the requests, it would be preferable to use those threads to hold the resource.

Is there a way to do this?

**Comment by LordFokas** [comment]
IIRC each client socket has its own thread (which is kept while the socket is alive), which means new threads are created when new clients connect or if a client sends a request after keep-alive expires.

There have been talks about ThreadPools before but I don't think those were implemented, the model I described above is the last I'm aware of.

Mapping resources to non-threadpooled asynchronous requests may be extremely difficult, but if you find it to be easier you're welcome to upgrade the current code base to use a ThreadPool with a configurable size, and then it'd be easy to map Resource copies to Threads :smiley:

**Comment by johann-petrak** [comment]
I am using the example from the Wiki to use a thread pool, but to be honest, without fully understanding it yet: https://github.com/NanoHttpd/nanohttpd/wiki/Example:-Using-a-ThreadPool
In this case, I assume the life-cycle of the threads would be different and span the whole lifetime of the server from when they are created?

In any case, for both approaches, it would be ideal if it was possible to have resources per thread and for serve to access those resources. Essentially what we want is a way to put the resource into the thread runner when the thread is created, access it from serve while it is running, and shut down the resource when the server is shut down. 

I did not figure out yet how the threads for each ClientHandler relate to the method serve and how serve could access anything from the ClientHandler in which it apparently should run. 
If serve could access the runner of the particular thread from the thread it is running in I think it may be possible to implement this without too much effort (maybe adding something to allow callbacks for initialization and shutdown of per-thread resources).

**Comment by LordFokas** [comment]
Yes, using a ThreadPool creates threads that span the lifetime of the server, that is entirely the point as creating a thread has a big inherent overhead, and so pools should be used for thread-intensive jobs like answering web requests on a server.

Having a `Map<Thread, MyResourceCopyContainer> resources` is a simple solution to do this because then you can simply do this:
```
private Resource getResource(Object resourceDescriptor){
    MyResourceCopyContainer container = resources.get(Thread.getCurrentThread());
    return container.getResource(resourceDescriptor);
}
```

This assumes you code a `MyResourceCopyContainer` that tracks resources and their respective local-thread copy, which gives you a bit more work but also enables you to do Just-In-Time copies of resources, which means a resource doesn't get copied into the local thread container until it is requested, which means (depending on what your threads are doing) you'll save CPU time and memory by never copying resources you never need to use. Also, IMO, it seems like a fairly simple and effective solution.
