### ISSUE TITLE
Make it possible to bind to a specific host ip address

### ISSUE THREAD

**Issue by johann-petrak** [NanoHttpd/nanohttpd#354]
On a machine with several IP addresses,  it would be good if we could bind to a specific address. Currently it is only possible to bind to a specific hostname, but not every IP address needs to be associated with a hostname. 

So alternately to the constructor that uses a String hostname and the port number, we could have another constructor that uses an InetAddress IP address and the port number.

**Comment by LordFokas** [comment]
Since there seems to be such a great need for ServerSocket configuration for so many users, it would perhaps be better if we could add a constructor that accepts an already constructed ServerSocket so that everyone can fully costumize it as they wish (and even extend) instead of asking about it every now and then.

What do you think @ritchieGitHub @elonen ?
This would also have to extend into NanoWSD as well as every other server like Nanolets and such.

**Comment by LordFokas** [comment]
Since I've been messing with NanoHTTPD v3.0 I realized this doesn't make sense. You can already set your own server socket factory that constructs a ServerSocket with any configuration you want, including SSL support.

I am, therefore, closing this as all support you need is already there.
