### ISSUE TITLE
DNS support

### ISSUE THREAD

**Issue by KalpeshVedak** [NanoHttpd/nanohttpd#359]
Is it possible to have support of DNS so we can use a domain name instead of an IP ?

**Comment by LordFokas** [comment]
What exactly do you mean? To connect to the NanoHTTPD server?

**Comment by KalpeshVedak** [comment]
Yes instead of using IP

**Comment by LordFokas** [comment]
NanoHTTPD has full support for that, as do most likely every single other network software ever.

DNS is a simple mapping protocol that matches a name with an IP, so that addresses can be more friendly to humans. In the end clients still have to fetch the IP for a domain name to connect to it, even though the user doesn't see it, because all connections must use IP addresses since that's the way the TCP/IP network stack works.

In order to have a domain available globally you need to purchase a domain name to a DNS provider in the internet, however if you want to test it locally you can change the local mapping on a windows computer by editing the file `C:\Windows\system32\drivers\etc\hosts` (the file has no extension but you can open it with notepad). There is a similar method for Linux distros but I'm not sure where the file is (I'd risk saying somewhere inside `/etc/`).

Anyways, and to sum up, DNS works on a network level and has nothing to do with software, so NanoHTTPD is already as compatible as it needs to be.

I hope I answered your questions and removed any possible doubts. :)

**Comment by KalpeshVedak** [comment]
Thank you Sir,

I will give it a shot based on your guidance.
