### ISSUE TITLE
question - websocket & http in one port

### ISSUE THREAD

**Issue by publicocean0** [NanoHttpd/nanohttpd#381]
hi, it is possible to receive http / websocket in a unique socket port? i saw there are 2 different servers for http and ws.

**Comment by LordFokas** [comment]
Yes, it is.

Just create a NanoWSD (websockets) server subclass and override both `openSocket()` and `serveHttp()`.
The first handles new websockets while the seconds handles non-websocket http requests :)

(I made that myself, with the same intent. Before that you could not cleanly serve http on a ws server).
You'll have a single server (nanowsd) in, say, port 80, but it will distinguish between http and ws requests and handle them accordingly. The default behavior for http in a ws server is to return a 404, but since `serveHttp()` was added you can just override that and code it just like `serve()` on NanoHTTPD.

**Comment by publicocean0** [comment]
cool :) i think i will use your library. I need to realize a http/ws proxy. probably i need to add a thread pool but i saw it is simple in your code.

**Comment by publicocean0** [comment]
Observing NanoWSD already now has method ....
protected Response serveHttp(final IHTTPSession session) {
        return super.serve(session);
    }

calling serve...

**Comment by LordFokas** [comment]
NanoHTTPD's serve returns a 404, which NanoWSD calls in serveHttp. You don't actually want to override NanoWSD's serve because that's what handles websockets, be careful with that.

Now, if your questions are answered you should close the issue yourself :)

**Comment by publicocean0** [comment]
thanks
