### ISSUE TITLE
SocketTimeoutException when reading content length is unknown

### ISSUE THREAD

**Issue by saket** [NanoHttpd/nanohttpd#609]
Is it a known issue that `nanohttpd` fails to read content body of multipart calls when their content length is unknown?

**Comment by joelcho** [comment]
I think it will never happen. Because [getBodySize](https://github.com/NanoHttpd/nanohttpd/blob/efb2ebf85a2b06f7c508aba9eaad5377e3a01e81/core/src/main/java/org/nanohttpd/protocols/http/HTTPSession.java#L593)  has checked the 'content-length'

And see also [parseBody](https://github.com/NanoHttpd/nanohttpd/blob/efb2ebf85a2b06f7c508aba9eaad5377e3a01e81/core/src/main/java/org/nanohttpd/protocols/http/HTTPSession.java#L621)
