### ISSUE TITLE
Android Sqlite BeginTransaction Deadlock

### ISSUE THREAD

**Issue by arvinboggs** [NanoHttpd/nanohttpd#85]
Succeeding call to the nanohttpd server after Sqlite BeginTransaction (from a previous nanohttpd server call) will result in SqliteConnectionPool deadlock.

Test file: https://gist.github.com/arvinboggs/7922214

Steps to recreate:
1.) Call the nanohttpd serve in Android from another device.
2.) nanohttpd instance should execute an Sqlite BeginTransaction
3.) Again, call the nanohttpd serve in Android from another device.
4.) nanohttpd instance should execute an Sqlite query.
5.) PROBLEM: that query will never finish.

**Comment by ritchieGitHub** [comment]
Could you please elaborate in more detail what you mean? I suspect you have a threading problem in your code.. or what is your request what we should change?

**Comment by ravenchild** [comment]
This is happening because you're starting a transaction and never finishing it and then queueing subsequent serve() requests after the transaction (on different threads). Remove the beginTransaction() and you should be fine. The SQLite database should be locked for the duration of a transaction. Also, why are you selecting in a transaction? The select should block writes for the statement's execution.

**Comment by ritchieGitHub** [comment]
closed, because no response for almost a year
